import Head from 'next/head'
import React from 'react'
import Header from './Header'

function Layout({ title, children }) {
    return (
        <>
            <Head>
                <title>{title ? title + " - Motta" : "Motta"}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex flex-col justify-between min-h-screen '>
                <Header />
                <main className='m-auto mt-10 px-4 ml-56'>
                    {children}
                </main>
                <></>
            </div>
        </>
    )
}

export default Layout